### ISSUE TITLE
Week 1 and 2: Scrum Reports 

### ISSUE THREAD

**Issue by jason0770** [VexMihir/chessApp#1]
Name: Jason Lai 
CSID: p9v2b
Scrum Reports:
1. What did you work on this past iteration (2 weeks)? 
     - Attended the weekly meetings.
     - Proposed a project idea called "Animal Management".
     - Presented a portion of our Project Progress 1 document, specifically focusing on the minimal project task requirements.
2. What were any major issues/challenges you ran into? 

3. What do you plan to work on for this coming iteration (2 weeks)? 
     - Finish the Minimal Requirement 1: Allowing people to play Chess games over the internet and the Minimal Requirement 3: Be able to represent a chess game on a UI using React and CSS.

Update Time: 11:01 am May 29, 2023, PT: Sorry for the late update, but I would like to cite the tool I used: Grammarly because I used it to improve my sentences.

**Comment by jason0770** [comment]
Name: Jason Lai 
CSID: p9v2b
Scrum Reports:
1. What did you work on this past iteration (2 weeks)? 
- Joined the weekly meetings
- Proposed a project idea [Animal Management]
- Presented a part of project progress 1[Project Design Document - Project task requirements - Minimal Requirements].
2. What were any major issues/challenges you ran into? 

3. What do you plan to work on for this coming iteration (2 weeks)? 
 - Finish the minimal requirements of Game Logic and UI for React.

**Comment by AlexNgGit** [comment]
Name: Alex
CSID: b7e6r

1) What did you work on this past iteration (2 weeks)?

Drafted and proposed an idea called "Management app" for group project
Wrote and presented one of break down tasks for project proposal.

2) What do you plan to work on for this coming iteration (2 weeks)?

Continue to discuss about tech stack and technical side of the project.
Learn about the new tech stacks.

Challenge:

Unfamiliar with most of tech stack.

**Comment by VexMihir** [comment]
Name: Mihir Bhandari
CSID: s5z2b
Scrum Reports:

1. What did you work on this past iteration (2 weeks)?

Attended the weekly meetings.
Proposed a project idea called "Travel Planner".
Presented a portion of our Project Progress 1 document, specifically focusing on the standard project task requirements.

2. What were any major issues/challenges you ran into?
-
3. What do you plan to work on for this coming iteration (2 weeks)?

Investigate and research and finalize the technologies and packages to be used to satisfy the minimal requirements. Work to start making the frontend of our chessApp MVP

**Comment by kdang243** [comment]
Name: Kevin Dang (Duc Anh Dang)
CSID: q7x2b


1. This past iteration, I came up with an idea for what our project should be as we had decided to all come up with a seperate one and decide on an idea as a group. My idea was of a Restaurant Booking System where we could book a restaurant without calling, be able to see availability and etc of a restaurant. Our group decided to do a Chess Application instead.

For the chess app, this first two weeks, we planned our goals and requirements for the project. I drew a rough sketch (you can see this in the read me) for how our UI would look in different views of the game.

2. One major challenge faced was that we don't know how big the project is supposed to be (or what would be a suitable size of project for the time we have.) I found it difficult to suggest features for our application when we had a hard time judging what scale the project should be at.

3. This next iteration, I believe we first need to decide the roles that we will take in the project first. Then plan how the project should be structured and the workflow (what needs to be done first etc). For this project I want to work on the backend more, and assuming that I am able to do this, I would mainly work on the chess game itself, as I have had some experience in working with a chess app.

**Comment by wallstarr** [comment]
Name: Dan Blustein
CSID: i5v2b

**What did you work on this past iteration (2 weeks)?**

Proposed the Chess App idea, and also wrote up a design document detailing the functionality of the website and the general technical ties to various frameworks. 

**What were any major issues/challenges you ran into?**
Not much -- so far I think we have done well. However, the work that remains to be done (technical investigation, MVP) are clear goals that need to be accomplished somewhat soon. 

**What do you plan to work on for this coming iteration (2 weeks)?**

I think in the first week it is most fruitful and prudent to write up all of the technical aspects of the project first without coding. Going through potential technical difficulties we might encounter, how we should approach various parts of the project, etc. In the second week, it makes sense to begin working on the MVP.
