### ISSUE TITLE
Scrum Report W5-6

### ISSUE THREAD

**Issue by jason0770** [VexMihir/chessApp#17]
Name: Jason Lai
csid: p9v2b
1. What did you work on this past iteration (2 weeks)? 
a. Some logic of Chessboard and 1 action.
b. Convert FEN to 2D Array and vice versa.
3. What were any major issues/challenges you ran into?
a. Chess piece valid move and Castaling and EnPassant 
5. What do you plan to work on for this coming iteration (2 weeks)? 
a. Complete Chessboard and things 
b. figure out how to connect the joinRoom/createRoom to a game room 
c. other requirements

**Comment by AlexNgGit** [comment]
Name: Alex Nguyen
csid: b7e6r

What did you work on this past iteration (2 weeks)?

- Previous game view basic functionalities, added 5 actions to meet the requirements.
- Communicating with Jason on overall structure of redux, and suggest using chessboard.jsx library.
- Added a query page component and its basic functionalities.

What were any major issues/challenges you ran into?

- On going health issue from last few weeks persistent, but tolerable and manageable at the moment.
-  Relatively difficult to get proper feedback and response from Jason when communication is needed for an agreement.

What do you plan to work on for this coming iteration (2 weeks)?

- Starting to add proper style and introduce a more cohesive appearance to assigned components.
- Working on the rest of previous game's view extra features  including hightlight algebraic notation, add hyperlink and actions to it, add extra sub-components such usernames and maybe look into available chess analysis API.
- Working on join room component if Jason hasn't worked on it.

**Comment by VexMihir** [comment]
Name: Mihir Bhandari
csid: s5z2b

What did you work on this past iteration (2 weeks)?

Worked to extend our socket room implementation to add disconnect handling, spectators, and username functionalities.

What were any major issues/challenges you ran into?
Not much, time commitment was less due to upcoming finals.

What do you plan to work on for this coming iteration (2 weeks)?

Connect the working sockets to the frontend. Add MongoDB functionality to the application to store chess games.

**Comment by wallstarr** [comment]
Name: Dan Blustein
csid: i5v2b

What did you work on this past iteration (2 weeks)?
Socket.io game functionality, mainly with regards to URLs, state, gameovers, etc.

What were any major issues/challenges you ran into?
Difficulties with socket.io, just long and tedious at times

What do you plan to work on for this coming iteration (2 weeks)?
Integration with chess logic and frontend UI

Sorry for being late.

**Comment by kdang243** [comment]
Name: Kevin Dang
csid: q7x2b

What did you work on this past iteration (2 weeks)?

Organised the backend for the chess game to fit specification needed from the frontend.

What were any major issues/challenges you ran into?
No major issues

What do you plan to work on for this coming iteration (2 weeks)?
Looking into storing FEN strings successfully into dynamoDB
