### ISSUE TITLE
Scrum Report W7-8

### ISSUE THREAD

**Issue by jason0770** [VexMihir/chessApp#21]
Name: Jason Lai
CSID: p9v2b
Scrum Reports:

What did you work on this past iteration (3 weeks)?
1. Built Chessboard UI and In-Game Sideboard
2. Added functionality that enables users to see any valid moves when they click a chess piece on a chessboard.
3. Integrated my frontend code with the backend with Socket.io

What were any major issues/challenges you ran into?
1. My code does not match my teammate's code style. I need to be assertive to talk to the backend teammates and ask if they could modify the backend code to match my code. 
2. The chess libraries can have some bugs and have no desired functionalities I want. I learned that I need to know what I can do with them.

What do you plan to work on for this coming iteration (2 weeks)?
1. Complete the rest of the proposed project requirements.
2. Write more collaborative code.
3. Add other non-proposed project functionalities or requirements to go beyond the requirements if the rest of the proposed project requirements are done.

Updated at July 30 2023 Sunday, Changed from 3 weeks to 2 weeks.

**Comment by AlexNgGit** [comment]
Name: Alex Nguyen
csid: b7e6r

What did you work on this past iteration (3 weeks)?

1. Finished room assignment as a whole.
2. Parsed mongodb data to display and integrated it into prevMoveList. Query page also has now a page pagination.
3. PrevMoveList is now to able show past moves and highlight current SAN (short algebraic notation).


What were any major issues/challenges you ran into?

1. The health issue got worse and affected the quality of the design preview presentation.
2. Resorted to report a difficult issue and everything is resolved now.
3. Styling is difficult and even more difficult to get a specific result. 

What do you plan to work on for this coming ?

1. Get some big rest.
2. Fix the table in the query page and added some minor styles here and there.
3. Probably implement the login system frontend if that is still in plan.

**Comment by kdang243** [comment]
Name: Kevin Dang
csid: q7x2b

What did you work on this past iteration (3 weeks)?

Created endpoints for MongoDB, allowing our backend to push the full game state after each game is finished to the DB. As well as allowing our frontend to retrieve both the full list of documents available in the DB or a singular document with an exact ID.

What were any major issues/challenges you ran into?

No major problems on my end. Just a minor one trying to use MongoDB's uri in the .env file.

What do you plan to work on for this coming ?

Maybe work on MongoDB endpoints for when we add a login system.
Assist on the finishing touches for the frontend or where ever more man power is needed

**Comment by wallstarr** [comment]
Name: Dan Blustein
csid: i5v2b

What did you work on this past iteration (3 weeks)?
1. Socket.io was the main thing. I mainly finished getting full game functionality working (checkmate/draws).
2. Assisting with MongoDB endpoint implementation for Kevin

What were any major issues/challenges you ran into?
1. None in particular.

What do you plan to work on for this coming sprint?
1. Offered draws/resignation
2. Connecting sockets (frontend integration)! We were unable to do that this sprint due to the frontend still needing work. 
3. Backend cleanup.

**Comment by VexMihir** [comment]
Name: Mihir Bhandari
csid: s5z2b

What did you work on this past iteration (3 weeks)?

Refactored the game logic in the backend and added timer functionality and events needed for the frontend
Setting up MongoDB endpoints
What were any major issues/challenges you ran into?

None in particular.
What do you plan to work on for this coming sprint?

Look into adding login functionality and
Connecting sockets (frontend integration)!
Backend refactoring and error handling.
