### ISSUE TITLE
Final Scrum Report

### ISSUE THREAD

**Issue by AlexNgGit** [VexMihir/chessApp#40]
Csid: b7e6r
name: Alex Nguyen

What did you work on this past iteration (2 weeks)?

Documented my code.
Finished AI feature and every components I have been assigned.
Fixed bugs with my team
Prepare my presentation and practice it with my team.

What were any major issues/challenges you ran into?
A last minute conflict with Jason but everything is over now.
AI feature can be confusing at first and I have to speedrun myself a bit.

What do you plan to work on for this coming sprint (hypothetically) ?

I probably personalize the website to my taste. Yes, the pink-fication will happen xD.

I probably will add an authorization system and have private routing across website.

I need to fix the routing issues with Render too.

======

Appreciation moment:

Thank you everyone for the time you have time spent working with me. I was learning a lot and was in awe of everyone's contribution and attention to the project.

**Comment by jason0770** [comment]
Csid: p9v2b
name: Jason Lai

What did you work on this past iteration (2 weeks)?
1. Added code comments to my code.
2. Tried to do the login system.
3. Enhanced my communication skills and software collaborative methodology.
4. Prepare my presentation and practice it with my team.

What were any major issues/challenges you ran into?
1. Did not clearly tell what I need in terms of communication but assumed that they all know me or assumed that Lecturers or TAs told my teammates already before assigning them to me and thought that I do not need to explain.
2. Did not understand socket.io.

What do you plan to work on for this coming sprint (hypothetically)?
1. Understand the socket.io, and collaborated with Dan to fix the socket.io-related bugs
2. Asked Kevin if I could have database schemas like Users, Rooms, and Games to incorporate with the login system and room assignment components
3. Redesign the room assignment components if getting Alex's permission.
4. Follow what Mihir says but make sure I understand what he says and make sure that there is no misunderstanding between us. 
5. Should build a system like a list of known bugs, what should each teammate accomplish every day.

Appreciation moment:
Thanks for everyone working with me. I ended up learning a lot of software collaborative methodology. I am happy with what I have done for my final presentation demo.

**Comment by kdang243** [comment]
Csid: q7x2b
name: Kevin Dang

What did you work on this past iteration (2 weeks)?

Documented my code.
Cleaned up any messy code that I saw in the repo.
Identified bugs in the project and debugged them with my team.
Prepared for the final demo and did a few practice runs with the team.

What were any major issues/challenges you ran into?
Conflicts with Mihir in terms of projects contributions and timing but it seems to be resolved now.
There were multiple bugs in both frontend and backend logic but we figured it out as a team.

What do you plan to work on for this coming sprint (hypothetically) ?

Personalize the frontend to my taste, the current one looks great! But I wanna make it mine haha.

I would add a chess bot that you could play against, using the minimax algorithm.

======

Appreciation moment:

Thank you everyone, I had a good time getting to know everyone and to work with you! I was able to learn a lot both technically and intrapersonally. I wish you all the best in the future.

**Comment by VexMihir** [comment]
Csid: s5z2b
name: Mihir Bhandari

What did you work on this past iteration (2 weeks)?

Finished revamping the UI
Documented and cleaned up the code
Fixed bugs with my team
Demo practice

What were any major issues/challenges you ran into?
Last minute bug flurry as Jason decided to change/add some features close to the deadline but was all fixed in due time thanks to the support of the team.
Some intra-team conflicts as the pressure ramped up for the showcase.

What do you plan to work on for this coming sprint (hypothetically)?

Add a login and auth system and adjust the project appropriately.

Restructure the FE.

======

Appreciation moment:

Thank you all for your efforts and contributions. Learned a lot and was excited to be working on a project of a bigger scale. I wish everyone luck in their future endeavours.

**Comment by wallstarr** [comment]
CSID: i5v2b
Name: Dan Blustein

**What did you work on this past iteration (2 weeks)?**
The primary work being done was fixing bugs, especially those involved with the Analysis View. 
Organized/led group meetings for the demo/presentation.
Added logic for custom time control/increments. 


**What were any major issues/challenges you ran into?**
A chaotic ending for sure... bug fixes were needed up until the very end, which was not ideal. But, it ended up being resolved, and the final product ended up in good shape :) 
Unaligned views between team members were difficult to get past and resolve, but, we eventually said what needed to be said and it ended up working out. 

**What do you plan to work on for this coming sprint (hypothetically)?**
Personally, I will be creating my own version of the frontend, as I would like to get some more React experience :)

But if this were a hypothetical real job and I were still in charge of doing more backend stuff, I would love to begin adding some form of Auth and preparing some sort of doc to present to the team regarding how that changes what already exists (a lot.)

In retrospect, for management purposes, I honestly think creating a JIRA board would have been super useful. I would honestly prioritize heavily that if this were a startup kind of deal. 

======

**Appreciation moment:**
I appreciate all of the effort from everyone towards the end for the presentation, it was good seeing all hands on deck for that :)
